import React, { useEffect } from 'react';
import Head from "next/head";
import LandingHeader from '../components/LandingPages/LandingHeader';
import Navigation from '../components/LandingPages/Navigation';
import LandingFeatures from '../components/LandingPages/LandingFeatures';
import LandingTabs from '../components/LandingPages/LandingTabs';
import LandingAbout from "../components/LandingPages/LandingAbout";
import Footer from '../components/LandingPages/Footer';

export default function Home() {

	return (
		<div>
			<Head>
				<title>Postrai - AI Data Generation</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="pai-landing page">
					<div className="pai-navigation">
						<Navigation />
					</div>
					<header className="pai-header">
						<LandingHeader />
					</header>
					<section className="pai-features">
						<LandingFeatures />
					</section>
					<section className="pai-tabs">
						<LandingTabs />
					</section>
					<section className="pai-content">
						<LandingAbout />
					</section>
					<Footer />
				</div>
			</main>
		</div>
	);
}
