import React, { useEffect } from 'react';
import Head from "next/head";
import Navigation from '../components/LandingPages/Navigation';
import Footer from '../components/LandingPages/Footer';
import Pricing from "../components/LandingPages/Pricing";
import Faq from "../components/LandingPages/Faq";

export default function pricing() {
	return (
		<div>
			<Head>
				<title>Pricing - Postrai</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="pai-landing page">
					<div className="pai-navigation">
						<Navigation />
					</div>
					<header className="pai-pricing">
						<Pricing />
					</header>
					<section className="pai-faq">
						<Faq />
					</section>
					<Footer />
				</div>
			</main>
		</div>
	)
}
